// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4fZB7OZmMpdIL5cxLtC8wMOVDC5dUkEA',
    appId: '1:185352644800:web:5e64424016bb3303b12525',
    messagingSenderId: '185352644800',
    projectId: 'tubulert-cd32b',
    authDomain: 'tubulert-cd32b.firebaseapp.com',
    storageBucket: 'tubulert-cd32b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsdENGFG_JISMqae0X62l6TKobfP1WCU4',
    appId: '1:185352644800:android:4fafe4a5ae9001c5b12525',
    messagingSenderId: '185352644800',
    projectId: 'tubulert-cd32b',
    storageBucket: 'tubulert-cd32b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDosG4lWJS_e7kG9oMitigZfBsu0y8j31I',
    appId: '1:185352644800:ios:90984ccf9049c03fb12525',
    messagingSenderId: '185352644800',
    projectId: 'tubulert-cd32b',
    storageBucket: 'tubulert-cd32b.firebasestorage.app',
    iosBundleId: 'com.example.tubulertWebAp',
  );
}
